#ifndef ACP_COMMAND_COMMON_H
#define ACP_COMMAND_COMMON_H

enum ACPCommandE {
	CMD_NONE = 0,
//====================COMMON==============================
	CMD_GET_ID_EXISTS,

//====================APP==================================================
	CMD_SET_APP_ID,//broadcast
	CMD_SET_APP_CHANNEL_ID_FIRST,
	CMD_APP_CHANNEL_ADD,
	CMD_APP_CHANNEL_DELETE,
	CMD_APP_STEP_ADD,
	CMD_APP_STEP_DELETE,
	CMD_APP_RESET,

	CMD_SET_APP_SERIAL_RATE,
	CMD_SET_APP_SERIAL_CONFIG,
	CMD_SET_APP_SERIAL_KIND,

	CMD_GET_APP_VARIABLES,

	CMD_GET_APP_ID,//broadcast
	CMD_GET_APP_CHANNEL_ID_FIRST,
	CMD_GET_APP_STATE,
	CMD_GET_APP_ERROR,

	CMD_GET_APP_SERIAL_RATE,
	CMD_GET_APP_SERIAL_CONFIG,
	CMD_GET_APP_SERIAL_KIND,

//====================CHANNEL==================================================
	CMD_CHANNEL_START,
	CMD_CHANNEL_STOP,
	CMD_CHANNEL_RELOAD,

	CMD_SET_CHANNEL_ID,
	CMD_GET_CHANNEL_ID,

	CMD_SET_CHANNEL_SAVE_GOAL,
	CMD_GET_CHANNEL_SAVE_GOAL,
	CMD_GETR_CHANNEL_SAVE_GOAL,

	CMD_SET_CHANNEL_DEVICE_KIND,
	CMD_GET_CHANNEL_DEVICE_KIND,
	CMD_GETR_CHANNEL_DEVICE_KIND,
	
	CMD_SET_CHANNEL_PIN,
	CMD_GET_CHANNEL_PIN,
	CMD_GETR_CHANNEL_PIN,
	
	CMD_SET_CHANNEL_GOAL,
	CMD_GET_CHANNEL_GOAL,
	CMD_GETR_CHANNEL_GOAL,
	
	CMD_GETR_CHANNEL_FTS,
	CMD_GETR_CHANNEL_STATE,
	CMD_GETR_CHANNEL_ERROR,
	CMD_GETR_CHANNEL_ENABLE,

//====================PWM==================================================
	CMD_SET_PWM_RESOLUTION,
	CMD_SET_PWM_PERIOD,
	CMD_SET_PWM_PW_MIN,
	CMD_SET_PWM_PW_MAX,

	CMD_GET_PWM_RESOLUTION,
	CMD_GET_PWM_PERIOD,
	CMD_GET_PWM_PW_MIN,
	CMD_GET_PWM_PW_MAX,

	CMD_GETR_PWM_RESOLUTION,
	CMD_GETR_PWM_PERIOD,
	CMD_GETR_PWM_PW_MIN,
	CMD_GETR_PWM_PW_MAX,

//====================REG==================================================
	CMD_SET_POS2_HYS,
	CMD_SET_POS2_OUT_MIN,
	CMD_SET_POS2_OUT_MAX,
	CMD_SET_POS2_MODE,

	CMD_SET_PID_KP,
	CMD_SET_PID_KI,
	CMD_SET_PID_KD,
	CMD_SET_PID_OUT_MIN,
	CMD_SET_PID_OUT_MAX,
	CMD_SET_PID_MODE,

	CMD_SET_REG_METHOD,


	CMD_GET_POS2_HYS,
	CMD_GET_POS2_OUT_MIN,
	CMD_GET_POS2_OUT_MAX,
	CMD_GET_POS2_MODE,

	CMD_GET_PID_KP,
	CMD_GET_PID_KI,
	CMD_GET_PID_KD,
	CMD_GET_PID_OUT_MIN,
	CMD_GET_PID_OUT_MAX,
	CMD_GET_PID_MODE,

	CMD_GET_REG_METHOD,

	CMD_GETR_POS2_HYS,
	CMD_GETR_POS2_OUT_MIN,
	CMD_GETR_POS2_OUT_MAX,
	CMD_GETR_POS2_MODE,

	CMD_GETR_PID_KP,
	CMD_GETR_PID_KI,
	CMD_GETR_PID_KD,
	CMD_GETR_PID_OUT_MIN,
	CMD_GETR_PID_OUT_MAX,
	CMD_GETR_PID_MODE,

	CMD_GETR_REG_METHOD,

//====================REMOTE==================================================
	CMD_SET_REM_ID,
	CMD_SET_REM_INTERVAL,
	CMD_SET_REM_SERIAL,

	CMD_SET_RSENSOR_ID,
	CMD_SET_RSENSOR_INTERVAL,
	CMD_SET_RSENSOR_SERIAL,

	CMD_GET_REM_ID,
	CMD_GET_REM_INTERVAL,
	CMD_GET_REM_SERIAL,

	CMD_GET_RSENSOR_ID,
	CMD_GET_RSENSOR_INTERVAL,
	CMD_GET_RSENSOR_SERIAL,

	CMD_GETR_REM_ID,
	CMD_GETR_REM_INTERVAL,
	CMD_GETR_REM_SERIAL,
	CMD_GETR_REM_STATE,
	CMD_GETR_REM_ERROR,

	CMD_GETR_RSENSOR_ID,
	CMD_GETR_RSENSOR_INTERVAL,
	CMD_GETR_RSENSOR_SERIAL,
	CMD_GETR_RSENSOR_STATE,
	CMD_GETR_RSENSOR_ERROR,

//====================RTC==================================================
	CMD_SET_RTC_DATE,
	CMD_SET_RTC_TIME,
	CMD_GET_RTC_DATE,
	CMD_GET_RTC_TIME,

//====================SECURE==================================================
	CMD_SET_SEC_ENABLE,
	CMD_SET_SEC_TM,
	CMD_SET_SEC_OUT,

	CMD_GET_SEC_ENABLE,
	CMD_GET_SEC_TM,
	CMD_GET_SEC_OUT,

	CMD_GETR_SEC_ENABLE,
	CMD_GETR_SEC_TM,
	CMD_GETR_SEC_OUT,
	CMD_GETR_SEC_STATE,

//====================SERVO==================================================
	CMD_SET_SERVO_PW_MIN,
	CMD_SET_SERVO_PW_MAX,
	CMD_SET_SERVO_IN_MIN,
	CMD_SET_SERVO_IN_MAX,

	CMD_GET_SERVO_PW_MIN,
	CMD_GET_SERVO_PW_MAX,
	CMD_GET_SERVO_IN_MIN,
	CMD_GET_SERVO_IN_MAX,

	CMD_GETR_SERVO_PW_MIN,
	CMD_GETR_SERVO_PW_MAX,
	CMD_GETR_SERVO_IN_MIN,
	CMD_GETR_SERVO_IN_MAX,

//====================TIMER==================================================
	CMD_SET_TIMER_TIME_ON,
	CMD_SET_TIMER_TIME_OFF,
	CMD_SET_TIMER_OUTPUT_ON,
	CMD_SET_TIMER_OUTPUT_OFF,
	CMD_SET_TIMER_INTERVAL_ON,
	CMD_SET_TIMER_INTERVAL_OFF,

	CMD_GET_TIMER_TIME_ON,
	CMD_GET_TIMER_TIME_OFF,
	CMD_GET_TIMER_OUTPUT_ON,
	CMD_GET_TIMER_OUTPUT_OFF,
	CMD_GET_TIMER_INTERVAL_ON,
	CMD_GET_TIMER_INTERVAL_OFF,

	CMD_GETR_TIMER_TIME_ON,
	CMD_GETR_TIMER_TIME_OFF,
	CMD_GETR_TIMER_OUTPUT_ON,
	CMD_GETR_TIMER_OUTPUT_OFF,
	CMD_GETR_TIMER_INTERVAL_ON,
	CMD_GETR_TIMER_INTERVAL_OFF,
	
	CMD_GATEWAY_PRINT,
	CMD_GATEWAY_RESET
};

#endif 
