#ifndef ONE_WIRE_MULTITASK_COMMON_H
#define ONE_WIRE_MULTITASK_COMMON_H

enum {
	OWIRE_DONE,
	OWIRE_NOT_FOUND,
	OWIRE_WAIT,
	OWIRE_BUSY,
	OWIRE_ERROR_QUEUE,
	OWIRE_ERROR_NO_PULLUP,
	OWIRE_ERROR_NO_DEVICE,
	OWIRE_ERROR_TIMEOUT
};

#define OW_CMD_READ_ROM		0x33
#define OW_CMD_MATCH_ROM	0x55
#define OW_CMD_SKIP_ROM		0xCC

#endif
