#ifndef APP_SERIAL_CONFIG_H
#define APP_SERIAL_CONFIG_H

typedef struct {
	int rate;
	int config;
	int kind;//APP_SERIAL_KIND_SERVER or APP_SERIAL_KIND_CLIENT or APP_SERIAL_KIND_DEBUG
	int id;
} AppSerialConfig;

#define APPCONFIGSR_GET_FIELD_FUNC(FIELD) appcgfsf ## FIELD
#define APPCONFIGSR_DEF_GET_FIELD_FUNC(FIELD) int APPCONFIGSR_GET_FIELD_FUNC(FIELD)(AppSerialConfig *item){return item->FIELD;}
#define APPCONFIGSR_DEC_GET_FIELD_FUNC(FIELD) extern int APPCONFIGSR_GET_FIELD_FUNC(FIELD)(AppSerialConfig *item);

#define APPCONFIGSR_SET_FIELD_FUNC(FIELD) appcsfsf ## FIELD
#define APPCONFIGSR_DEF_SET_FIELD_FUNC(FIELD) void APPCONFIGSR_SET_FIELD_FUNC(FIELD)(AppSerialConfig *item, int v){item->FIELD = v;}
#define APPCONFIGSR_DEC_SET_FIELD_FUNC(FIELD) extern void APPCONFIGSR_SET_FIELD_FUNC(FIELD)(AppSerialConfig *item, int v);

APPCONFIGSR_DEC_GET_FIELD_FUNC(rate)
APPCONFIGSR_DEC_GET_FIELD_FUNC(config)
APPCONFIGSR_DEC_GET_FIELD_FUNC(kind)

APPCONFIGSR_DEC_SET_FIELD_FUNC(rate)
APPCONFIGSR_DEC_SET_FIELD_FUNC(config)
APPCONFIGSR_DEC_SET_FIELD_FUNC(kind)


#endif
