#ifndef ACP_COMMAND_H
#define ACP_COMMAND_H

enum ACPCommandE {
	CMD_NONE = 0,
	CMD_GATEWAY_RESET,
	CMD_GATEWAY_PRINT,
	CMD_APP_GET_ID, //broadcast
	CMD_AOID_GET_FIRST,
	CMD_AOID_GET_NEXT,
	CMD_AOID_GET_ACP_COMMAND_SUPPORTED_FIRST,
	CMD_AOID_GET_ACP_COMMAND_SUPPORTED_NEXT,
	CMD_AOID_SET_RAM_VALUE,
	CMD_AOID_SET_NVRAM_VALUE,
	CMD_AOID_GET_RAM_VALUE,
	CMD_AOID_GET_NVRAM_VALUE,
	CMD_AOID_DELETE,
	CMD_AOID_ADD,
	CMD_AOID_START,
	CMD_AOID_STOP,
	CMD_AOID_RESET,
	CMD_NOID_GET_FIRST,
	CMD_NOID_GET_NEXT,
	CMD_NOID_GET_ACP_COMMAND_SUPPORTED_FIRST,
	CMD_NOID_GET_ACP_COMMAND_SUPPORTED_NEXT,
	CMD_NOID_GET_EXISTS,
	CMD_NOID_GET_FTS,
	CMD_NOID_GET_STATE,
	CMD_NOID_GET_ERROR,
	CMD_NOID_GET_DEVICE_KIND,
	CMD_NOID_START,
	CMD_NOID_STOP,
	CMD_NOID_RESET,
	CMD_NOID_SET_GOAL,
	CMD_NOID_SET_TEXT,
	CMD_NOID_SET_TEXT_BLINK
};

#endif 
